### ISSUE TITLE
lua 位运算符的问题

### ISSUE THREAD

**Issue by lvOvOvl** [wenlifan/SensitiveWordFilter#1]
string_split.lua 文件中 utf8_to_unicode 方法
"&" 运算符 和 "<<", ">>" 运算符 在 lua 不是不能用吗 或者怎么用

**Comment by lvOvOvl** [comment]
哦我知道了 你的 lua 版本应该是 5.3 的 我的是 5.1 的没有这些运算符

**Comment by wenlifan** [comment]
你咋还是5.1 呀！现在都5.4了。
